spring:
  kafka:
    bootstrap-servers: localhost:9092
  mvc:
    format:
      date-time: iso
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/appdatabase?authSource=admin
  jpa:
    generate-ddl: true
  datasource:
    url: jdbc:postgresql://localhost:5432/booking_db
    username: postgres
    password: postgres
    hikari:
      schema: booking_schema
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS booking_schema
      connection-timeout: 10000

app:
  kafka:
    kafkaMessageUserRegisterTopic: "user-register"
    kafkaMessageNewBookingTopic: "new-booking"
    kafkaMessageGroupId: "kafka-message-group-id"